name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
        # python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Set up Python # ${{ matrix.python-version }}
        # with:
        #   python-version: ${{ matrix.python-version }}

      - name: Install pytorch
        run: python -m pip install torch torchvision

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* pp27-*"  # skip Python 2.7 wheels

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
