name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        # python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Set up Python # ${{ matrix.python-version }}
        # with:
        #   python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_SKIP: "cp27-* pp27-* cp35-* cp39-*"  # skip Python 2.7 wheels
          CIBW_BEFORE_BUILD_LINUX: bash scripts/pre_build.sh && pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/libtorch/lib && echo $LD_LIBRARY_PATH
          # CIBW_ENVIRONMENT: 
          # CIBW_BEFORE_BUILD_MACOS: pip install torch
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
